### ISSUE TITLE
Issue parsing a cookie in v. 1.0.1

### ISSUE THREAD

**Issue by magalnick** [jshttp/cookie#196] opened 2024-10-13 07:10 UTC
Hello, I'm also having an issue in v. `1.0.1` with parsing a cookie value.

The cookie value in the request header is:
```
token=0ee158e2-e267-436d-af58-c2239ac03ea7
```

The code attempting to parse this is:
```typescript
import cookie from "cookie";
...
if (request.headers["cookie"]) {
    context.params.cookies = cookie.parse(request.headers["cookie"]);
}
...
```

This throws an error referencing the line number of the `parse` command:
```
error: TypeError: Cannot read properties of undefined (reading 'parse')
```

This worked as expected until I upgraded to `1.0.1`. When I downgraded back to `0.6.0`, it started working again.

Thank you for looking into this issue.

**Comment by blakeembrey** [comment] 2024-10-13 16:27
Duplicate of https://github.com/jshttp/cookie/issues/195

**Closed by blakeembrey** 2024-10-13 16:27 UTC
