### ISSUE TITLE
Why is the cookie name not decoded (like the value)?

### ISSUE THREAD

**Issue by yvele** [jshttp/cookie#114] opened 2020-10-23 17:37 UTC
I'm using jshttp/cookie server side (within an [AWS Lambda@Edge](https://aws.amazon.com/lambda/edge/) function) to parse cookies.
I'm not personally handling the cookie creation and I only want to parse it.

Cookie names created by my vendor contains special characters that are encoded.

I would have the option to get the decoded cookie names like how it is done with the cookie values.

Is this behaviour by design? Is it legitimate to decode the cookie name when parsing?

If so, is cookie name decoding a feature that you may consider?

**Comment by yvele** [comment] 2020-10-25 11:26
Also the decode function should accept an array of name/value tuples (like how it has been suggested for serialisation https://github.com/jshttp/cookie/issues/30) 🤔

**Comment by GrosSacASac** [comment] 2020-12-23 13:19
Good question

**Comment by dougwilson** [comment] 2022-03-30 05:06
I'm going to close this for now since the question was answered.

I'll also add that it was probably not added since decoding of a name would probably complicate adding them to an object. It is likely decoding/encoding the value (at least by default) will eventually be removed, as it has had multiple issues opened that it is unexpected behavior. The RFC does state that servers SHOULD encoding the cookie value if needed, but makes no such statement on the cookie value, so seems to fall outside the cookie spec to mess with the cookie name.

**Closed by dougwilson** 2022-03-30 05:06 UTC
Labels: question
