### ISSUE TITLE
import cookie from 'cookie' resolve as undefined, missing default export

### ISSUE THREAD

**Issue by alexandre-combemorel** [jshttp/cookie#198] opened 2024-10-18 09:09 UTC
I had an issue when building my app with vite, as the export default is missing, vite is actually not able to import the package and resolve it as undefined.

Would it be possible to add an export default ?

index.js:
```
Object.defineProperty(exports, "__esModule", { value: true });
exports.parse = parse;
exports.serialize = serialize;
```

**Comment by blakeembrey** [comment] 2024-10-18 16:26
Probably a duplicate of https://github.com/jshttp/cookie/issues/195. Have you tried using the named imports instead? Not everything needs a default export.

**Closed by blakeembrey** 2024-10-18 16:26 UTC
