### ISSUE TITLE
Default export missing

### ISSUE THREAD

**Issue by fabb** [jshttp/cookie#197] opened 2024-10-14 10:28 UTC
Since the update to 1.0.0, the default export is missing, but the types suggest it is available.

```
import cookie from 'cookie'
...
cookie.parse(someValue)
```

This will not throw a typescript error, but it will crash at runtime. Worked fine before 1.0.0.

**Comment by blakeembrey** [comment] 2024-10-14 15:09
Duplicate of https://github.com/jshttp/cookie/issues/195. Sounds like you may have a typescript issue, the types don’t indicate a default export.

**Closed by blakeembrey** 2024-10-14 15:09 UTC

**Comment by blakeembrey** [comment] 2024-10-14 16:42
It might be this option hiding the error: https://www.typescriptlang.org/tsconfig/#allowSyntheticDefaultImports

I’m not sure beyond this, maybe related to esModuleInterop. I can’t tell without more to debug with.
