### ISSUE TITLE
Can't use as ES Module in Babel project in cookie==1.0.1

### ISSUE THREAD

**Issue by SeanHayes** [jshttp/cookie#203] opened 2024-10-30 17:48 UTC
When I use `import cookie from 'cookie';` in my babel project, when I call `cookie.parse('some string') I get:
`TypeError: Cannot read properties of undefined (reading 'parse')`

Any tips for getting this to work? Here's my babel.config.js:
```
module.exports = function (api) {
    api.cache(true);

    return {
        "presets": [
            [
                "@babel/preset-env",
                {
                    "useBuiltIns": "entry",
                    "targets": {
                        "node": "current"
                    },
                    "ignoreBrowserslistConfig": true
                }
            ]
        ],
        "ignore": [],
        "plugins": [
            ["babel-plugin-transform-import-meta"],
            ["module-resolver", {
              "root": ["./src/**"],
              "alias": {
                "~": "./",
              }
            }],
            [
                "@babel/plugin-transform-runtime",
                {
                    "corejs": false,
                    "helpers": true,
                    "regenerator": true
                }
            ],
            "inferno",
            ["@babel/plugin-proposal-decorators", {
                "version": "legacy"
            }],
            [
                "babel-plugin-inline-import",
                {
                    "extensions": [
                        ".csv",
                        ".txt"
                    ]
                }
            ],
            ["inline-json-import", {}],
            [
                "babel-plugin-transform-require-ignore",
                {
                    "extensions": [
                        ".css",
                        ".scss",
                        ".worker.js"
                    ]
                }
            ],
            "dynamic-import-node"
        ]
    };
}
```

**Comment by blakeembrey** [comment] 2024-10-30 20:09
Please see how to import it in the README. Duplicate of https://github.com/jshttp/cookie/issues/195.

**Closed by blakeembrey** 2024-10-30 20:09 UTC
